@baseUrl = http://localhost:52858/TeleoptiWFM/Web/ChangePassword
@email = emil.sundin@teleopti.com

# @name DebugCreate
POST {{baseUrl}}/DebugCreate HTTP/1.1
Content-Type: application/json

{ "Email": "{{email}}" }

###

# @name RequestReset
POST {{baseUrl}}/RequestReset HTTP/1.1
Content-Type: application/json

{ "Email": "{{email}}" }

###

# @name ValidateToken
POST {{baseUrl}}/ValidateToken HTTP/1.1
Content-Type: application/json

{ "ResetToken": {{DebugCreate.response.body.*}} }

### 

# @name Reset
POST {{baseUrl}}/Reset HTTP/1.1
Content-Type: application/json

{
    "ResetToken": {{DebugCreate.response.body.*}},
    "NewPassword": "secret"
}