@ECHO OFF

SET VS2017_PATH=%PROGRAMFILES(X86)%\Microsoft Visual Studio\2017\
SET MSBUILD_PATH=\MSBuild\15.0\Bin\MSBuild.exe

IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (
   SET MSBUILD_PATH=\MSBuild\15.0\Bin\amd64\MSBuild.exe
)

SET MSBUILD="empty"
IF EXIST "%VS2017_PATH%BuildTools%MSBUILD_PATH%" (
SET MSBUILD="%VS2017_PATH%BuildTools%MSBUILD_PATH%"
) ELSE (
	IF EXIST "%VS2017_PATH%Enterprise%MSBUILD_PATH%" (
		SET MSBUILD="%VS2017_PATH%Enterprise%MSBUILD_PATH%") ELSE (
			IF EXIST "%VS2017_PATH%Professional%MSBUILD_PATH%" (
			SET MSBUILD="%VS2017_PATH%Professional%MSBUILD_PATH%"
		)
	)
)

SET MSBUILD_PATH=
SET VS2017_PATH=
SET MSBUILD=%MSBUILD:"=%
IF "%MSBUILD%"=="empty" (
	SET /A ERRORLEVEL=999
)