@ECHO OFF
SETLOCAL

SET ROOTDIR=%~dp0
SET ROOTDIR=%ROOTDIR:~0,-1%

SET BASELINE_NAME=%1
IF "%BASELINE_NAME%"=="" SET BASELINE_NAME=DemoSales

CALL :Branch %~dp0..
SET CCC7DB=%Branch%_%BASELINE_NAME%_TeleoptiCCC7
SET AnalyticsDB=%Branch%_%BASELINE_NAME%_TeleoptiAnalytics

CALL %ROOTDIR%\FixMyConfig.bat %CCC7DB% %AnalyticsDB%

:Branch
SET BRANCH=%~n1
SET BRANCH=%BRANCH%%~x1
GOTO :EOF

ENDLOCAL