// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Teleopti.Ccc.WebBehaviorTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Preferences feedback")]
    public partial class PreferencesFeedbackFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PreferencesFeedback.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Preferences feedback", "In order to know at which times I might work\r\nAs an agent\r\nI want feedback for my" +
                    " preferences", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day without restrictions")]
        public virtual void FeedbackForADayWithoutRestrictions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day without restrictions", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am an agent");
#line 8
 testRunner.And("I have a shift bag with start times 8 to 9 and end times 16 to 17");
#line 9
 testRunner.When("I view preferences");
#line 10
 testRunner.Then("I should see the start time boundry 8 to 9");
#line 11
 testRunner.And("I should see the end time boundry 16 to 17");
#line 12
 testRunner.And("I should see the contract time boundry 7 to 9");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with day off preference")]
        public virtual void FeedbackForADayWithDayOffPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with day off preference", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am an agent");
#line 19
 testRunner.And("I have a shift bag");
#line 20
 testRunner.And("I have preference with day off");
#line 21
 testRunner.When("I view preferences");
#line 22
 testRunner.Then("I should see no feedback");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with absence preference")]
        public virtual void FeedbackForADayWithAbsencePreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with absence preference", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("I am an agent");
#line 26
 testRunner.And("I have a shift bag");
#line 27
 testRunner.And("I have preference with absence");
#line 28
 testRunner.When("I view preferences");
#line 29
 testRunner.Then("I should see no feedback");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with shift category preference")]
        public virtual void FeedbackForADayWithShiftCategoryPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with shift category preference", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I am an agent");
#line 33
 testRunner.And("I have a shift bag");
#line 34
 testRunner.And("I have preference with shift category AM");
#line 35
 testRunner.When("I view preferences");
#line 36
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts of category AM");
#line 37
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts of category AM");
#line 38
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts of category AM");
#line 39
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts of category AM");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with start time limitation preference")]
        public virtual void FeedbackForADayWithStartTimeLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with start time limitation preference", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("I am an agent");
#line 43
 testRunner.And("I have a shift bag");
#line 44
 testRunner.And("I have a preference with start time limitation between 7:00 and 10:00");
#line 45
 testRunner.When("I view preferences");
#line 46
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 47
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 48
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 49
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with end time limitation preference")]
        public virtual void FeedbackForADayWithEndTimeLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with end time limitation preference", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.Given("I am an agent");
#line 53
 testRunner.And("I have a shift bag");
#line 54
 testRunner.And("I have a preference with end time limitation between 13:00 and 19:00");
#line 55
 testRunner.When("I view preferences");
#line 56
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 57
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 58
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 59
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with work time limitation preference")]
        public virtual void FeedbackForADayWithWorkTimeLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with work time limitation preference", ((string[])(null)));
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I am an agent");
#line 63
 testRunner.And("I have a shift bag");
#line 64
 testRunner.And("I have a preference with work time limitation between 7 and 9 hours");
#line 65
 testRunner.When("I view preferences");
#line 66
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 67
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 68
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 69
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with lunch start time limitation preference")]
        public virtual void FeedbackForADayWithLunchStartTimeLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with lunch start time limitation preference", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I am an agent");
#line 73
 testRunner.And("I have a shift bag");
#line 74
 testRunner.And("I have a preference with lunch start time limitation between 11:00 and 12:00");
#line 75
 testRunner.When("I view preferences");
#line 76
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 77
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 78
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 79
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with lunch end time limitation preference")]
        public virtual void FeedbackForADayWithLunchEndTimeLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with lunch end time limitation preference", ((string[])(null)));
#line 81
this.ScenarioSetup(scenarioInfo);
#line 82
 testRunner.Given("I am an agent");
#line 83
 testRunner.And("I have a shift bag");
#line 84
 testRunner.And("I have a preference with lunch end time limitation between 12:00 and 13:00");
#line 85
 testRunner.When("I view preferences");
#line 86
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 87
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 88
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 89
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with lunch length limitation preference")]
        public virtual void FeedbackForADayWithLunchLengthLimitationPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with lunch length limitation preference", ((string[])(null)));
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("I am an agent");
#line 93
 testRunner.And("I have a shift bag");
#line 94
 testRunner.And("I have a preference with lunch length limitation between 1 and 2 hours");
#line 95
 testRunner.When("I view preferences");
#line 96
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 97
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 98
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 99
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with availability")]
        public virtual void FeedbackForADayWithAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with availability", ((string[])(null)));
#line 104
this.ScenarioSetup(scenarioInfo);
#line 105
 testRunner.Given("I am an agent");
#line 106
 testRunner.And("I have a shift bag");
#line 107
 testRunner.And("I have availability");
#line 108
 testRunner.When("I view preferences");
#line 109
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts that match the ava" +
                    "ilability");
#line 110
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts that match the avail" +
                    "ability");
#line 111
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts that match the " +
                    "availability");
#line 112
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts that match the " +
                    "availability");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with start time limitation availability")]
        public virtual void FeedbackForADayWithStartTimeLimitationAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with start time limitation availability", ((string[])(null)));
#line 114
this.ScenarioSetup(scenarioInfo);
#line 115
 testRunner.Given("I am an agent");
#line 116
 testRunner.And("I have a shift bag");
#line 117
 testRunner.And("I have a availability with start time limitation of 7:00 at the earliest");
#line 118
 testRunner.When("I view preferences");
#line 119
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 120
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 121
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 122
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with end time limitation availability")]
        public virtual void FeedbackForADayWithEndTimeLimitationAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with end time limitation availability", ((string[])(null)));
#line 124
this.ScenarioSetup(scenarioInfo);
#line 125
 testRunner.Given("I am an agent");
#line 126
 testRunner.And("I have a shift bag");
#line 127
 testRunner.And("I have a availability with end time limitation of 20:00 at the latest");
#line 128
 testRunner.When("I view preferences");
#line 129
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 130
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 131
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 132
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with work time limitation availability")]
        public virtual void FeedbackForADayWithWorkTimeLimitationAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with work time limitation availability", ((string[])(null)));
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("I am an agent");
#line 136
 testRunner.And("I have a shift bag");
#line 137
 testRunner.And("I have a availability with work time limitation between 7 and 9 hours");
#line 138
 testRunner.When("I view preferences");
#line 139
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts matching the prefe" +
                    "rence");
#line 140
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts matching the prefere" +
                    "nce");
#line 141
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line 142
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts matching the pr" +
                    "eference");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with availability and preference")]
        public virtual void FeedbackForADayWithAvailabilityAndPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with availability and preference", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 147
 testRunner.Given("I am an agent");
#line 148
 testRunner.And("I have a shift bag");
#line 149
 testRunner.And("I have availability");
#line 150
 testRunner.And("I have preference with shift category AM");
#line 151
 testRunner.When("I view preferences");
#line 152
 testRunner.Then("I should see the start time boundry for the shift bag\'s shifts of category AM and" +
                    " that match the availability");
#line 153
 testRunner.And("I should see the end time boundry for the shift bag\'s shifts of category AM and t" +
                    "hat match the availability");
#line 154
 testRunner.And("I should see the minimum contract time for the shift bag\'s shifts of category AM " +
                    "and that match the availability");
#line 155
 testRunner.And("I should see the maximum contract time for the shift bag\'s shifts of category AM " +
                    "and that match the availability");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with a schedule")]
        public virtual void FeedbackForADayWithASchedule()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with a schedule", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("I am an agent");
#line 161
 testRunner.And("I have a shift");
#line 162
 testRunner.When("I view preferences");
#line 163
 testRunner.Then("I should see the start time of the shift");
#line 164
 testRunner.And("I should see the end time of the shift");
#line 165
 testRunner.And("I should see the contract time of the shift");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Feedback for a day with a schedule, preference and availability")]
        public virtual void FeedbackForADayWithASchedulePreferenceAndAvailability()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Feedback for a day with a schedule, preference and availability", ((string[])(null)));
#line 167
this.ScenarioSetup(scenarioInfo);
#line 168
 testRunner.Given("I am an agent");
#line 169
 testRunner.And("I have a shift");
#line 170
 testRunner.And("I have a shift bag");
#line 171
 testRunner.And("I have preference for shift category AM");
#line 172
 testRunner.And("I have availability");
#line 173
 testRunner.When("I view preferences");
#line 174
 testRunner.Then("I should see the start time of the shift");
#line 175
 testRunner.And("I should see the end time of the shift");
#line 176
 testRunner.And("I should see the contract time of the shift");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
