// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.296
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Teleopti.Ccc.WebBehaviorTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Preferences Extended")]
    public partial class PreferencesExtendedFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PreferencesExtended.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Preferences Extended", "In order to view and submit when I prefer to work in more detail\r\nAs an agent\r\nI " +
                    "want to view and submit extended preferences", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Name",
                        "Access to extended preferences"});
            table1.AddRow(new string[] {
                        "Access to extended preferences",
                        "true"});
#line 9
 testRunner.Given("there is a role with", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Name",
                        "No access to extended preferences"});
            table2.AddRow(new string[] {
                        "Access to extended preferences",
                        "false"});
#line 13
 testRunner.And("there is a role with", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Name",
                        "Late"});
#line 17
 testRunner.And("there is a shift category with", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Name",
                        "Lunch"});
#line 20
 testRunner.And("there is an activity with", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Name",
                        "Dayoff"});
#line 23
 testRunner.And("there is a dayoff with", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Name",
                        "Illness"});
#line 26
 testRunner.And("there is an absence with", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Name",
                        "Published schedule"});
            table7.AddRow(new string[] {
                        "Schedule published to date",
                        "2012-06-24"});
            table7.AddRow(new string[] {
                        "Available shift category",
                        "Late"});
            table7.AddRow(new string[] {
                        "Available dayoff",
                        "Dayoff"});
            table7.AddRow(new string[] {
                        "Available absence",
                        "Illness"});
            table7.AddRow(new string[] {
                        "Available activity",
                        "Lunch"});
#line 29
 testRunner.And("I have a workflow control set with", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "Start date",
                        "2012-06-18"});
            table8.AddRow(new string[] {
                        "Type",
                        "Week"});
            table8.AddRow(new string[] {
                        "Length",
                        "1"});
#line 37
 testRunner.And("I have a schedule period with", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "Start date",
                        "2012-06-18"});
#line 42
 testRunner.And("I have a person period with", ((string)(null)), table9, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see indication of an extended preference")]
        public virtual void CanSeeIndicationOfAnExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see indication of an extended preference", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 47
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.And("I have an extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.When("I view preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("I should see that I have an extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see extended preference")]
        public virtual void CanSeeExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see extended preference", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 53
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("I have an extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.When("I view preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.And("I click the extended preference indication on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.Then("I should see the extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see extended preference without permission")]
        public virtual void CanSeeExtendedPreferenceWithoutPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see extended preference without permission", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 60
 testRunner.Given("I have the role \'No access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
 testRunner.And("I have an extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.When("I view preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.And("I click the extended preference indication on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.Then("I should see the extended preference on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can not add extended preference without permission")]
        public virtual void CanNotAddExtendedPreferenceWithoutPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can not add extended preference without permission", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 70
 testRunner.Given("I have the role \'No access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.When("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.Then("I should not see the extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add standard preference")]
        public virtual void AddStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add standard preference", ((string[])(null)));
#line 74
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 75
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.And("I am viewing preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("I select day \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.And("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Preference",
                        "Late"});
#line 79
 testRunner.And("I input extended preference fields with", ((string)(null)), table10, "And ");
#line 82
 testRunner.And("I click the apply extended preferences button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.Then("I should not see an extended preference indication on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.And("I should see the preference \'Late\' on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add extended preference")]
        public virtual void AddExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add extended preference", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 87
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
 testRunner.And("I am viewing preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.When("I select day \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.And("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table11.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table11.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table11.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table11.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table11.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table11.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table11.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table11.AddRow(new string[] {
                        "Activity Start time minimum",
                        "11:30"});
            table11.AddRow(new string[] {
                        "Activity Start time maximum",
                        "11:45"});
            table11.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:00"});
            table11.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:15"});
            table11.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table11.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 91
 testRunner.And("I input extended preference fields with", ((string)(null)), table11, "And ");
#line 107
 testRunner.And("I click the apply extended preferences button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.And("I click the extended preference indication on \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "Date",
                        "2012-06-20"});
            table12.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table12.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table12.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table12.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table12.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table12.AddRow(new string[] {
                        "Work time minimum",
                        "8:00"});
            table12.AddRow(new string[] {
                        "Work time maximum",
                        "8:30"});
            table12.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table12.AddRow(new string[] {
                        "Activity Start time minimum",
                        "11:30"});
            table12.AddRow(new string[] {
                        "Activity Start time maximum",
                        "11:45"});
            table12.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:00"});
            table12.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:15"});
            table12.AddRow(new string[] {
                        "Activity time minimum",
                        "0:15"});
            table12.AddRow(new string[] {
                        "Activity time maximum",
                        "0:45"});
#line 109
 testRunner.Then("I should see extended preference with", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add extended preference when span to next day")]
        public virtual void AddExtendedPreferenceWhenSpanToNextDay()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add extended preference when span to next day", ((string[])(null)));
#line 127
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 128
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
 testRunner.And("I am viewing preferences for date \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.When("I select day \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
 testRunner.And("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "End time minimum",
                        "02:00"});
            table13.AddRow(new string[] {
                        "End time minimum next day",
                        "true"});
            table13.AddRow(new string[] {
                        "End time maximum",
                        "02:30"});
            table13.AddRow(new string[] {
                        "End time maximum next day",
                        "true"});
#line 132
 testRunner.And("I input extended preference fields with", ((string)(null)), table13, "And ");
#line 138
 testRunner.And("I click the apply extended preferences button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("I click the extended preference indication on \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table14.AddRow(new string[] {
                        "End time minimum",
                        "02:00 +1"});
            table14.AddRow(new string[] {
                        "End time maximum",
                        "02:30 +1"});
#line 140
 testRunner.Then("I should see extended preference with", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View available preference list when adding extended preference")]
        public virtual void ViewAvailablePreferenceListWhenAddingExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View available preference list when adding extended preference", ((string[])(null)));
#line 146
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 147
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 148
 testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.And("I click the extended preference select-box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table15.AddRow(new string[] {
                        "Late"});
            table15.AddRow(new string[] {
                        "Dayoff"});
            table15.AddRow(new string[] {
                        "Illness"});
#line 151
 testRunner.Then("I should see these available preferences", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View available activity list when adding extended preference")]
        public virtual void ViewAvailableActivityListWhenAddingExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View available activity list when adding extended preference", ((string[])(null)));
#line 157
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 158
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 159
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
 testRunner.And("I click the extended preference activity select-box", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table16.AddRow(new string[] {
                        "Lunch"});
#line 162
    testRunner.Then("I should see these available activities", ((string)(null)), table16, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Replace extended preference")]
        public virtual void ReplaceExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Replace extended preference", ((string[])(null)));
#line 166
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 167
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table17.AddRow(new string[] {
                        "IsExtended",
                        "true"});
            table17.AddRow(new string[] {
                        "Shift Category",
                        "Late"});
#line 168
    testRunner.And("I have an extended preference with", ((string)(null)), table17, "And ");
#line 173
    testRunner.And("I am viewing preferences for date \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 174
 testRunner.When("I select day \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 175
    testRunner.And("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table18.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table18.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table18.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table18.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table18.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table18.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table18.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table18.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table18.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table18.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table18.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table18.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table18.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 176
    testRunner.And("I input extended preference fields with", ((string)(null)), table18, "And ");
#line 192
    testRunner.And("I click the apply extended preferences button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
    testRunner.And("I click the extended preference indication on \'2012-09-05\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table19.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table19.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table19.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table19.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table19.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table19.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table19.AddRow(new string[] {
                        "Work time minimum",
                        "8:00"});
            table19.AddRow(new string[] {
                        "Work time maximum",
                        "8:30"});
            table19.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table19.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table19.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table19.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table19.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table19.AddRow(new string[] {
                        "Activity time minimum",
                        "0:15"});
            table19.AddRow(new string[] {
                        "Activity time maximum",
                        "0:45"});
#line 194
    testRunner.Then("I should see extended preference with", ((string)(null)), table19, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate preference times")]
        public virtual void ValidatePreferenceTimes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate preference times", ((string[])(null)));
#line 213
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 214
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 215
    testRunner.And("I am viewing preferences for date \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
    testRunner.When("I select day \'2012-06-20\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
    testRunner.And("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table20.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table20.AddRow(new string[] {
                        "Start time maximum",
                        "10:00"});
#line 218
    testRunner.And("I input extended preference fields with", ((string)(null)), table20, "And ");
#line 223
    testRunner.And("I click the apply extended preferences button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 224
    testRunner.Then("I should see add extended preferences panel with error \'Invalid time startTime\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable all time fields when absence preference is selected")]
        public virtual void DisableAllTimeFieldsWhenAbsencePreferenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable all time fields when absence preference is selected", ((string[])(null)));
#line 226
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 227
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 228
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 229
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table21.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 230
    testRunner.And("I input extended preference fields with", ((string)(null)), table21, "And ");
#line 233
    testRunner.Then("I should not be able to edit time fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable all time fields, when day off is selected")]
        public virtual void DisableAllTimeFieldsWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable all time fields, when day off is selected", ((string[])(null)));
#line 235
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 236
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 237
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 238
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 239
    testRunner.And("I input extended preference fields with", ((string)(null)), table22, "And ");
#line 242
    testRunner.Then("I should not be able to edit time fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset activity field when day off is selected")]
        public virtual void ResetActivityFieldWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset activity field when day off is selected", ((string[])(null)));
#line 244
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 245
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 246
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 247
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table23.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 248
    testRunner.And("I input extended preference fields with", ((string)(null)), table23, "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 251
    testRunner.And("I input extended preference fields with", ((string)(null)), table24, "And ");
#line 254
    testRunner.Then("I should see activity dropdown list selected to \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset time input fields when day off is selected")]
        public virtual void ResetTimeInputFieldsWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset time input fields when day off is selected", ((string[])(null)));
#line 256
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 257
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 258
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 259
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table25.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table25.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table25.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table25.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table25.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table25.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table25.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table25.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table25.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table25.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table25.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table25.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table25.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table25.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 260
    testRunner.And("I input extended preference fields with", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 276
    testRunner.And("I input extended preference fields with", ((string)(null)), table26, "And ");
#line 279
    testRunner.Then("all the time fields should be reset", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset time input fields when absence is selected")]
        public virtual void ResetTimeInputFieldsWhenAbsenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset time input fields when absence is selected", ((string[])(null)));
#line 281
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 282
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 283
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 284
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table27.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table27.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table27.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table27.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table27.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table27.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table27.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table27.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table27.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table27.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table27.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table27.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table27.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table27.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 285
    testRunner.And("I input extended preference fields with", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table28.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 301
    testRunner.And("I input extended preference fields with", ((string)(null)), table28, "And ");
#line 304
    testRunner.Then("all the time fields should be reset", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset activity field when absence is selected")]
        public virtual void ResetActivityFieldWhenAbsenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset activity field when absence is selected", ((string[])(null)));
#line 306
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 307
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 308
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 309
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table29.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 310
    testRunner.And("I input extended preference fields with", ((string)(null)), table29, "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table30.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 313
    testRunner.And("I input extended preference fields with", ((string)(null)), table30, "And ");
#line 316
    testRunner.Then("I should see activity dropdown list selected to \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Enable activity time fields when activity is selected")]
        public virtual void EnableActivityTimeFieldsWhenActivityIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enable activity time fields when activity is selected", ((string[])(null)));
#line 318
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 319
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 320
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 321
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table31.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 322
    testRunner.And("I input extended preference fields with", ((string)(null)), table31, "And ");
#line 325
    testRunner.Then("I should be able to edit activity minimum and maximum fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable activity time fields when no activity selected")]
        public virtual void DisableActivityTimeFieldsWhenNoActivitySelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable activity time fields when no activity selected", ((string[])(null)));
#line 327
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 328
    testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 329
    testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 330
    testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 331
    testRunner.Then("I should not be able to edit activity minimum and maximum fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset extended preference form")]
        public virtual void ResetExtendedPreferenceForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset extended preference form", ((string[])(null)));
#line 333
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 334
 testRunner.Given("I have the role \'Access to extended preferences\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 335
 testRunner.And("I am viewing preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 336
 testRunner.When("I click the add extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table32.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table32.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table32.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table32.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table32.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table32.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table32.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table32.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table32.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table32.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table32.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table32.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table32.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table32.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 337
 testRunner.And("I input extended preference fields with", ((string)(null)), table32, "And ");
#line 353
 testRunner.And("I click the reset extended preference button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 354
 testRunner.Then("I should see preference dropdown list selected to \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 355
 testRunner.And("all the time fields should be reset", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 356
 testRunner.And("I should see activity dropdown list selected to \" \"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 357
 testRunner.And("I should not be able to edit activity minimum and maximum fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
