// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Teleopti.Ccc.WebBehaviorTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Preferences Extended")]
    [NUnit.Framework.IgnoreAttribute()]
    public partial class PreferencesExtendedFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PreferencesExtended.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Preferences Extended", "In order to view and submit when I prefer to work in more detail\r\nAs an agent\r\nI " +
                    "want to view and submit extended preferences", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "Name",
                        "Access to extended preferences"});
            table1.AddRow(new string[] {
                        "Access to extended preferences",
                        "true"});
#line 10
 testRunner.Given("there is a role with", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Name",
                        "No access to extended preferences"});
            table2.AddRow(new string[] {
                        "Access to extended preferences",
                        "false"});
#line 14
 testRunner.And("there is a role with", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Name",
                        "Late"});
#line 18
 testRunner.And("there is a shift category with", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Name",
                        "Lunch"});
#line 21
 testRunner.And("there is an activity with", ((string)(null)), table4);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Name",
                        "Dayoff"});
#line 24
 testRunner.And("there is a dayoff with", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Name",
                        "Illness"});
#line 27
 testRunner.And("there is an absence with", ((string)(null)), table6);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Name",
                        "Published schedule"});
            table7.AddRow(new string[] {
                        "Schedule published to date",
                        "2012-06-24"});
            table7.AddRow(new string[] {
                        "Available shift category",
                        "Late"});
            table7.AddRow(new string[] {
                        "Available dayoff",
                        "Dayoff"});
            table7.AddRow(new string[] {
                        "Available absence",
                        "Illness"});
            table7.AddRow(new string[] {
                        "Available activity",
                        "Lunch"});
#line 30
 testRunner.And("I have a workflow control set with", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "Start date",
                        "2012-06-18"});
            table8.AddRow(new string[] {
                        "Type",
                        "Week"});
            table8.AddRow(new string[] {
                        "Length",
                        "1"});
#line 38
 testRunner.And("I have a schedule period with", ((string)(null)), table8);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "Start date",
                        "2012-06-18"});
#line 43
 testRunner.And("I have a person period with", ((string)(null)), table9);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see indication of an extended preference")]
        public virtual void CanSeeIndicationOfAnExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see indication of an extended preference", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 48
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 49
 testRunner.And("I have an extended preference on \'2012-06-20\'");
#line 50
 testRunner.When("I view preferences for date \'2012-06-20\'");
#line 51
 testRunner.Then("I should see that I have an extended preference on \'2012-06-20\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see extended preference")]
        public virtual void CanSeeExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see extended preference", ((string[])(null)));
#line 53
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 54
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 55
 testRunner.And("I have an extended preference on \'2012-06-20\'");
#line 56
 testRunner.When("I view preferences for date \'2012-06-20\'");
#line 57
 testRunner.And("I click the extended preference indication on \'2012-06-20\'");
#line 58
 testRunner.Then("I should see the extended preference on \'2012-06-20\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can see extended preference without permission")]
        public virtual void CanSeeExtendedPreferenceWithoutPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can see extended preference without permission", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 61
 testRunner.Given("I have the role \'No access to extended preferences\'");
#line 62
 testRunner.And("I have an extended preference on \'2012-06-20\'");
#line 63
 testRunner.When("I view preferences for date \'2012-06-20\'");
#line 64
 testRunner.And("I click the extended preference indication on \'2012-06-20\'");
#line 65
 testRunner.Then("I should see the extended preference on \'2012-06-20\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can not add extended preference without permission")]
        public virtual void CanNotAddExtendedPreferenceWithoutPermission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can not add extended preference without permission", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 71
 testRunner.Given("I have the role \'No access to extended preferences\'");
#line 72
 testRunner.When("I am viewing preferences");
#line 73
 testRunner.Then("I should not see the extended preference button");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add standard preference")]
        public virtual void AddStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add standard preference", ((string[])(null)));
#line 75
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 76
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 77
 testRunner.And("I am viewing preferences for date \'2012-06-20\'");
#line 78
 testRunner.When("I select day \'2012-06-20\'");
#line 79
 testRunner.And("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Preference",
                        "Late"});
#line 80
 testRunner.And("I input extended preference fields with", ((string)(null)), table10);
#line 83
 testRunner.And("I click the apply extended preferences button");
#line 84
 testRunner.Then("I should not see an extended preference indication on \'2012-06-20\'");
#line 85
 testRunner.And("I should see the preference \'Late\' on \'2012-06-20\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add extended preference")]
        public virtual void AddExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add extended preference", ((string[])(null)));
#line 87
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 88
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 89
 testRunner.And("I am viewing preferences for date \'2012-06-20\'");
#line 90
 testRunner.When("I select day \'2012-06-20\'");
#line 91
 testRunner.And("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table11.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table11.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table11.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table11.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table11.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table11.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table11.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table11.AddRow(new string[] {
                        "Activity Start time minimum",
                        "11:30"});
            table11.AddRow(new string[] {
                        "Activity Start time maximum",
                        "11:45"});
            table11.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:00"});
            table11.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:15"});
            table11.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table11.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 92
 testRunner.And("I input extended preference fields with", ((string)(null)), table11);
#line 108
 testRunner.And("I click the apply extended preferences button");
#line 109
 testRunner.And("I click the extended preference indication on \'2012-06-20\'");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "Date",
                        "2012-06-20"});
            table12.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table12.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table12.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table12.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table12.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table12.AddRow(new string[] {
                        "Work time minimum",
                        "8:00"});
            table12.AddRow(new string[] {
                        "Work time maximum",
                        "8:30"});
            table12.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table12.AddRow(new string[] {
                        "Activity Start time minimum",
                        "11:30"});
            table12.AddRow(new string[] {
                        "Activity Start time maximum",
                        "11:45"});
            table12.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:00"});
            table12.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:15"});
            table12.AddRow(new string[] {
                        "Activity time minimum",
                        "0:15"});
            table12.AddRow(new string[] {
                        "Activity time maximum",
                        "0:45"});
#line 110
 testRunner.Then("I should see extended preference with", ((string)(null)), table12);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add extended preference when span to next day")]
        public virtual void AddExtendedPreferenceWhenSpanToNextDay()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add extended preference when span to next day", ((string[])(null)));
#line 128
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 129
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 130
 testRunner.And("I am viewing preferences for date \'2012-09-05\'");
#line 131
 testRunner.When("I select day \'2012-09-05\'");
#line 132
 testRunner.And("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table13.AddRow(new string[] {
                        "End time minimum",
                        "02:00"});
            table13.AddRow(new string[] {
                        "End time minimum next day",
                        "true"});
            table13.AddRow(new string[] {
                        "End time maximum",
                        "02:30"});
            table13.AddRow(new string[] {
                        "End time maximum next day",
                        "true"});
#line 133
 testRunner.And("I input extended preference fields with", ((string)(null)), table13);
#line 139
 testRunner.And("I click the apply extended preferences button");
#line 140
 testRunner.And("I click the extended preference indication on \'2012-09-05\'");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table14.AddRow(new string[] {
                        "End time minimum",
                        "02:00 +1"});
            table14.AddRow(new string[] {
                        "End time maximum",
                        "02:30 +1"});
#line 141
 testRunner.Then("I should see extended preference with", ((string)(null)), table14);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View available preference list when adding extended preference")]
        public virtual void ViewAvailablePreferenceListWhenAddingExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View available preference list when adding extended preference", ((string[])(null)));
#line 147
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 148
 testRunner.Given("I have the role \'Access to extended preferences\'");
#line 149
 testRunner.And("I am viewing preferences");
#line 150
 testRunner.When("I click the add extended preference button");
#line 151
 testRunner.And("I click the extended preference select-box");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table15.AddRow(new string[] {
                        "Late"});
            table15.AddRow(new string[] {
                        "Dayoff"});
            table15.AddRow(new string[] {
                        "Illness"});
#line 152
 testRunner.Then("I should see these available preferences", ((string)(null)), table15);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View available activity list when adding extended preference")]
        public virtual void ViewAvailableActivityListWhenAddingExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View available activity list when adding extended preference", ((string[])(null)));
#line 158
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 159
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 160
    testRunner.And("I am viewing preferences");
#line 161
    testRunner.When("I click the add extended preference button");
#line 162
 testRunner.And("I click the extended preference activity select-box");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value"});
            table16.AddRow(new string[] {
                        "Lunch"});
#line 163
    testRunner.Then("I should see these available activities", ((string)(null)), table16);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Replace extended preference")]
        public virtual void ReplaceExtendedPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Replace extended preference", ((string[])(null)));
#line 167
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 168
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table17.AddRow(new string[] {
                        "IsExtended",
                        "true"});
            table17.AddRow(new string[] {
                        "Shift Category",
                        "Late"});
#line 169
    testRunner.And("I have an extended preference with", ((string)(null)), table17);
#line 174
    testRunner.And("I am viewing preferences for date \'2012-09-05\'");
#line 175
 testRunner.When("I select day \'2012-09-05\'");
#line 176
    testRunner.And("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table18.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table18.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table18.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table18.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table18.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table18.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table18.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table18.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table18.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table18.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table18.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table18.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table18.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 177
    testRunner.And("I input extended preference fields with", ((string)(null)), table18);
#line 193
    testRunner.And("I click the apply extended preferences button");
#line 194
    testRunner.And("I click the extended preference indication on \'2012-09-05\'");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table19.AddRow(new string[] {
                        "Date",
                        "2012-09-05"});
            table19.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table19.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table19.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table19.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table19.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table19.AddRow(new string[] {
                        "Work time minimum",
                        "8:00"});
            table19.AddRow(new string[] {
                        "Work time maximum",
                        "8:30"});
            table19.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table19.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table19.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table19.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table19.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table19.AddRow(new string[] {
                        "Activity time minimum",
                        "0:15"});
            table19.AddRow(new string[] {
                        "Activity time maximum",
                        "0:45"});
#line 195
    testRunner.Then("I should see extended preference with", ((string)(null)), table19);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate preference times")]
        public virtual void ValidatePreferenceTimes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate preference times", ((string[])(null)));
#line 214
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 215
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 216
    testRunner.And("I am viewing preferences for date \'2012-06-20\'");
#line 217
    testRunner.When("I select day \'2012-06-20\'");
#line 218
    testRunner.And("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table20.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table20.AddRow(new string[] {
                        "Start time maximum",
                        "10:00"});
#line 219
    testRunner.And("I input extended preference fields with", ((string)(null)), table20);
#line 224
    testRunner.And("I click the apply extended preferences button");
#line 225
    testRunner.Then("I should see add extended preferences panel with error \'Invalid time startTime\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable all time fields when absence preference is selected")]
        public virtual void DisableAllTimeFieldsWhenAbsencePreferenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable all time fields when absence preference is selected", ((string[])(null)));
#line 227
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 228
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 229
    testRunner.And("I am viewing preferences");
#line 230
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table21.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 231
    testRunner.And("I input extended preference fields with", ((string)(null)), table21);
#line 234
    testRunner.Then("I should not be able to edit time fields");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable all time fields, when day off is selected")]
        public virtual void DisableAllTimeFieldsWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable all time fields, when day off is selected", ((string[])(null)));
#line 236
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 237
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 238
    testRunner.And("I am viewing preferences");
#line 239
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 240
    testRunner.And("I input extended preference fields with", ((string)(null)), table22);
#line 243
    testRunner.Then("I should not be able to edit time fields");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset activity field when day off is selected")]
        public virtual void ResetActivityFieldWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset activity field when day off is selected", ((string[])(null)));
#line 245
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 246
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 247
    testRunner.And("I am viewing preferences");
#line 248
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table23.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 249
    testRunner.And("I input extended preference fields with", ((string)(null)), table23);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 252
    testRunner.And("I input extended preference fields with", ((string)(null)), table24);
#line 255
    testRunner.Then("I should see activity dropdown list selected to \" \"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset time input fields when day off is selected")]
        public virtual void ResetTimeInputFieldsWhenDayOffIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset time input fields when day off is selected", ((string[])(null)));
#line 257
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 258
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 259
    testRunner.And("I am viewing preferences");
#line 260
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table25.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table25.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table25.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table25.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table25.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table25.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table25.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table25.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table25.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table25.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table25.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table25.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table25.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table25.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 261
    testRunner.And("I input extended preference fields with", ((string)(null)), table25);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "Preference",
                        "Dayoff"});
#line 277
    testRunner.And("I input extended preference fields with", ((string)(null)), table26);
#line 280
    testRunner.Then("all the time fields should be reset");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset time input fields when absence is selected")]
        public virtual void ResetTimeInputFieldsWhenAbsenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset time input fields when absence is selected", ((string[])(null)));
#line 282
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 283
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 284
    testRunner.And("I am viewing preferences");
#line 285
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table27.AddRow(new string[] {
                        "Preference",
                        "Late"});
            table27.AddRow(new string[] {
                        "Start time minimum",
                        "10:30"});
            table27.AddRow(new string[] {
                        "Start time maximum",
                        "11:00"});
            table27.AddRow(new string[] {
                        "End time minimum",
                        "19:00"});
            table27.AddRow(new string[] {
                        "End time maximum",
                        "20:30"});
            table27.AddRow(new string[] {
                        "Work time minimum",
                        "08:00"});
            table27.AddRow(new string[] {
                        "Work time maximum",
                        "08:30"});
            table27.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
            table27.AddRow(new string[] {
                        "Activity Start time minimum",
                        "12:00"});
            table27.AddRow(new string[] {
                        "Activity Start time maximum",
                        "12:15"});
            table27.AddRow(new string[] {
                        "Activity End time minimum",
                        "12:30"});
            table27.AddRow(new string[] {
                        "Activity End time maximum",
                        "12:45"});
            table27.AddRow(new string[] {
                        "Activity time minimum",
                        "00:15"});
            table27.AddRow(new string[] {
                        "Activity time maximum",
                        "00:45"});
#line 286
    testRunner.And("I input extended preference fields with", ((string)(null)), table27);
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table28.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 302
    testRunner.And("I input extended preference fields with", ((string)(null)), table28);
#line 305
    testRunner.Then("all the time fields should be reset");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reset activity field when absence is selected")]
        public virtual void ResetActivityFieldWhenAbsenceIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reset activity field when absence is selected", ((string[])(null)));
#line 307
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 308
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 309
    testRunner.And("I am viewing preferences");
#line 310
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table29.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 311
    testRunner.And("I input extended preference fields with", ((string)(null)), table29);
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table30.AddRow(new string[] {
                        "Preference",
                        "Illness"});
#line 314
    testRunner.And("I input extended preference fields with", ((string)(null)), table30);
#line 317
    testRunner.Then("I should see activity dropdown list selected to \" \"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Enable activity time fields when activity is selected")]
        public virtual void EnableActivityTimeFieldsWhenActivityIsSelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Enable activity time fields when activity is selected", ((string[])(null)));
#line 319
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 320
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 321
    testRunner.And("I am viewing preferences");
#line 322
    testRunner.When("I click the add extended preference button");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table31.AddRow(new string[] {
                        "Activity",
                        "Lunch"});
#line 323
    testRunner.And("I input extended preference fields with", ((string)(null)), table31);
#line 326
    testRunner.Then("I should be able to edit activity minimum and maximum fields");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disable activity time fields when no activity selected")]
        public virtual void DisableActivityTimeFieldsWhenNoActivitySelected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disable activity time fields when no activity selected", ((string[])(null)));
#line 328
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 329
    testRunner.Given("I have the role \'Access to extended preferences\'");
#line 330
    testRunner.And("I am viewing preferences");
#line 331
    testRunner.When("I click the add extended preference button");
#line 332
    testRunner.Then("I should not be able to edit activity minimum and maximum fields");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
