// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Teleopti.Ccc.WebBehaviorTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Preferences")]
    public partial class PreferencesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Preferences.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Preferences", "In order to view and submit when I prefer to work\r\nAs an agent\r\nI want to view an" +
                    "d submit my work preferences", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View preferences")]
        public virtual void ViewPreferences()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View preferences", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am an agent");
#line 8
 testRunner.When("I view preferences");
#line 9
 testRunner.Then("I should see current or first future virtual schedule period +/- 1 week");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("See shift category preference")]
        public virtual void SeeShiftCategoryPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("See shift category preference", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I am an agent");
#line 13
 testRunner.And("I have existing shift category preference");
#line 14
 testRunner.When("I view preferences");
#line 15
 testRunner.Then("I should see my existing shift category preference");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("See day off preference")]
        public virtual void SeeDayOffPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("See day off preference", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am an agent");
#line 19
 testRunner.And("I have existing day off preference");
#line 20
 testRunner.When("I view preferences");
#line 21
 testRunner.Then("I should see my existing day off preference");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("See absence preference")]
        public virtual void SeeAbsencePreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("See absence preference", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I am an agent");
#line 25
 testRunner.And("I have existing absence preference");
#line 26
 testRunner.When("I view preferences");
#line 27
 testRunner.Then("I should see my existing absence preference");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No schedule period")]
        public virtual void NoSchedulePeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No schedule period", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I am an agent");
#line 31
 testRunner.And("I do not have a schedule period");
#line 32
 testRunner.When("I view preferences");
#line 33
 testRunner.Then("I should see a user-friendly message explaining I dont have anything to view");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No person period")]
        public virtual void NoPersonPeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No person period", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("I am an agent");
#line 37
 testRunner.And("I do not have a person period");
#line 38
 testRunner.When("I view preferences");
#line 39
 testRunner.Then("I should see a user-friendly message explaining I dont have anything to view");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No access to preferences menu item")]
        public virtual void NoAccessToPreferencesMenuItem()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No access to preferences menu item", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("I am an agent without access to preferences");
#line 43
 testRunner.When("I sign in");
#line 44
 testRunner.Then("I should not be able to see preferences link");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No access to preferences page")]
        public virtual void NoAccessToPreferencesPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No access to preferences page", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("I am an agent without access to preferences");
#line 48
 testRunner.When("I sign in");
#line 49
 testRunner.And("I navigate to the preferences page");
#line 50
 testRunner.Then("I should see an error message");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigate next virtual schedule period")]
        public virtual void NavigateNextVirtualSchedulePeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate next virtual schedule period", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("I am an agent");
#line 54
 testRunner.And("I have several virtual schedule periods");
#line 55
 testRunner.And("I am viewing preferences");
#line 56
 testRunner.When("I click next virtual schedule period button");
#line 57
 testRunner.Then("I should see next virtual schedule period");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigate previous virtual schedule period")]
        public virtual void NavigatePreviousVirtualSchedulePeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate previous virtual schedule period", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("I am an agent");
#line 61
 testRunner.And("I have several virtual schedule periods");
#line 62
 testRunner.And("I am viewing preferences");
#line 63
 testRunner.When("I click previous virtual schedule period button");
#line 64
 testRunner.Then("I should see previous virtual schedule period");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Select period from period-picker")]
        public virtual void SelectPeriodFromPeriod_Picker()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Select period from period-picker", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("I am an agent");
#line 68
 testRunner.And("I am viewing preferences");
#line 69
 testRunner.When("I open the period-picker");
#line 70
 testRunner.And("I click on any day of a week");
#line 71
 testRunner.Then("the period-picker should close");
#line 72
 testRunner.And("I should see the selected virtual schedule period");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View standard preference list")]
        public virtual void ViewStandardPreferenceList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View standard preference list", ((string[])(null)));
#line 79
this.ScenarioSetup(scenarioInfo);
#line 80
 testRunner.Given("I am an agent");
#line 81
 testRunner.And("I have an open workflow control set with an allowed standard preference");
#line 82
 testRunner.And("I am viewing preferences");
#line 83
 testRunner.When("I click the standard preference split-button");
#line 84
 testRunner.Then("I should see the workflow control set\'s standard preferences list");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remember selected standard preference")]
        public virtual void RememberSelectedStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remember selected standard preference", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
 testRunner.Given("I am an agent");
#line 88
 testRunner.And("I have an open workflow control set with an allowed standard preference");
#line 89
 testRunner.And("I am viewing preferences");
#line 90
 testRunner.When("I change standard preference");
#line 91
 testRunner.And("I click next virtual schedule period button");
#line 92
 testRunner.Then("I should see the selected standard preference in the split-button");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add standard preference")]
        public virtual void AddStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add standard preference", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line 95
 testRunner.Given("I am an agent");
#line 96
 testRunner.And("I have an open workflow control set with an allowed standard preference");
#line 97
 testRunner.And("I am viewing preferences");
#line 98
 testRunner.When("I select an editable day without preference");
#line 99
 testRunner.And("I select a standard preference");
#line 100
 testRunner.Then("I should see the standard preference in the calendar");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Replace standard preference")]
        public virtual void ReplaceStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Replace standard preference", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
 testRunner.Given("I am an agent");
#line 104
 testRunner.And("I have an open workflow control set with an allowed standard preference");
#line 105
 testRunner.And("I have existing standard preference");
#line 106
 testRunner.And("I am viewing preferences");
#line 107
 testRunner.When("I select an editable day with standard preference");
#line 108
 testRunner.And("I select a standard preference");
#line 109
 testRunner.Then("I should see the standard preference in the calendar");
#line 110
 testRunner.And("I should not see the former standard preference in the calendar");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Set multiple preference")]
        public virtual void SetMultiplePreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Set multiple preference", ((string[])(null)));
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
 testRunner.Given("I am an agent");
#line 114
 testRunner.And("I have an open workflow control set with an allowed standard preference");
#line 115
 testRunner.And("I have existing standard preference");
#line 116
 testRunner.And("I am viewing preferences");
#line 117
 testRunner.When("I select an editable day with standard preference");
#line 118
 testRunner.And("I also select an editable day without standard preference");
#line 119
 testRunner.And("I select a standard preference");
#line 120
 testRunner.Then("I should see the 2 standard preferences in the calendar");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete multiple standard preference")]
        public virtual void DeleteMultipleStandardPreference()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete multiple standard preference", ((string[])(null)));
#line 122
this.ScenarioSetup(scenarioInfo);
#line 123
 testRunner.Given("I am an agent");
#line 124
 testRunner.And("I have a workflow control set with open standard preference period");
#line 125
 testRunner.And("I have 2 existing standard preference");
#line 126
 testRunner.And("I am viewing preferences");
#line 127
 testRunner.When("I select 2 editable day with standard preference");
#line 128
 testRunner.And("I click the delete button");
#line 129
 testRunner.Then("I should no longer see the 2 standard preferences in the calendar");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can not edit preference without workflow control set")]
        public virtual void CanNotEditPreferenceWithoutWorkflowControlSet()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can not edit preference without workflow control set", ((string[])(null)));
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("I am an agent");
#line 136
 testRunner.And("I do not have a workflow control set");
#line 137
 testRunner.When("I view preferences");
#line 138
 testRunner.Then("I should see a message saying I am missing a workflow control set");
#line 139
 testRunner.And("the preference calendar should not be editable");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Display preference period information")]
        public virtual void DisplayPreferencePeriodInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display preference period information", ((string[])(null)));
#line 141
this.ScenarioSetup(scenarioInfo);
#line 142
 testRunner.Given("I am an agent");
#line 143
 testRunner.And("I have a workflow control set");
#line 144
 testRunner.When("I view preferences");
#line 145
 testRunner.Then("I should see the preference period information");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can not edit preference in closed period")]
        public virtual void CanNotEditPreferenceInClosedPeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can not edit preference in closed period", ((string[])(null)));
#line 147
this.ScenarioSetup(scenarioInfo);
#line 148
 testRunner.Given("I am an agent");
#line 149
 testRunner.And("I have a workflow control set with closed preference periods");
#line 150
 testRunner.When("I view preferences");
#line 151
 testRunner.Then("the preference calendar should not be editable");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can edit preference in open period")]
        public virtual void CanEditPreferenceInOpenPeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can edit preference in open period", ((string[])(null)));
#line 153
this.ScenarioSetup(scenarioInfo);
#line 154
 testRunner.Given("I am an agent");
#line 155
 testRunner.And("I have a workflow control set with open standard preference period");
#line 156
 testRunner.When("I view preferences");
#line 157
 testRunner.Then("the preference calendar should be editable");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Default to first virtual schedule period overlapping open preference period")]
        public virtual void DefaultToFirstVirtualSchedulePeriodOverlappingOpenPreferencePeriod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Default to first virtual schedule period overlapping open preference period", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("I am an agent");
#line 161
 testRunner.And("I have a workflow control set with preference periods open next month");
#line 162
 testRunner.When("I view preferences");
#line 163
 testRunner.Then("I should see the first virtual schedule period overlapping open preference period" +
                    "");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
