ALTER TABLE [dbo].[BusinessUnit] DROP CONSTRAINT [FK_BusinessUnit_Person_UpdatedBy]
ALTER TABLE [dbo].[WorkflowControlSet] DROP CONSTRAINT [FK_WorkflowControlSet_Person_UpdatedBy]
ALTER TABLE [dbo].[WorkflowControlSet] DROP CONSTRAINT [FK_WorkflowControlSet_Activity_AllowedPreferenceActivity]
ALTER TABLE [dbo].[ApplicationFunction] DROP CONSTRAINT [FK_ApplicationFunction_ApplicationFunction]
ALTER TABLE [dbo].[Person] DROP CONSTRAINT [FK_Person_Person_UpdatedBy]
ALTER TABLE [dbo].[Person] DROP CONSTRAINT [FK_Person_WriteProtection_UpdatedBy]
