EXEC sp_rename N'[dbo].[AlarmType]', N'RtaRule'
EXEC sp_rename N'[dbo].[RtaRule].[PK_AlarmType]', N'PK_RtaRule', N'INDEX'
EXEC sp_rename N'[FK_AlarmType_BusinessUnit]', N'FK_RtaRule_BusinessUnit', N'OBJECT'
EXEC sp_rename N'[FK_AlarmType_Person_UpdatedBy]', N'FK_RtaRule_Person_UpdatedBy', N'OBJECT'
EXEC sp_rename N'[dbo].[StateGroupActivityAlarm].[AlarmType]', N'RtaRule', N'COLUMN'
EXEC sp_rename N'[FK_StateGroupActivityAlarm_AlarmType]', N'FK_StateGroupActivityAlarm_RtaRule', N'OBJECT'