ALTER TABLE dbo.AgentState DROP PK_AgentState
GO

ALTER TABLE dbo.AgentState ADD CONSTRAINT PK_AgentState PRIMARY KEY CLUSTERED (PersonId)
WITH( ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF, FILLFACTOR = 50) 
GO

