DECLARE @default_state_group uniqueidentifier
DECLARE @platform_type_id uniqueidentifier
SET @default_state_group = (SELECT TOP 1 Id FROM RtaStateGroup WHERE DefaultStateGroup = 1 AND IsDeleted = 0)
SET @platform_type_id = '76330CAB-86FC-4FDC-989D-73CA6D5830A5' -- Symposium

IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'Logged Out' AND [StateCode] = '-1')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'Logged Out', '-1', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_EMERGENCY' AND [StateCode] = '1')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_EMERGENCY', '1', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_CONSULTATION' AND [StateCode] = '2')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_CONSULTATION', '2', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_CALL_PRESENT' AND [StateCode] = '4')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_CALL_PRESENT', '4', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_RESERVE' AND [StateCode] = '8')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_RESERVE', '8', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_IDLE' AND [StateCode] = '16')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_IDLE', '16', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_BRK' AND [StateCode] = '32')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_BRK', '32', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_NOTRDY' AND [StateCode] = '64')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_NOTRDY', '64', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_ONHOLD' AND [StateCode] = '128')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_ONHOLD', '128', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_ACTIVE' AND [StateCode] = '256')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_ACTIVE', '256', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DN_OUT_ONHOLD' AND [StateCode] = '512')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DN_OUT_ONHOLD', '512', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DN_OUT_ACTIVE' AND [StateCode] = '1024')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DN_OUT_ACTIVE', '1024', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DN_OUT_ACTIVE_ONHOLD' AND [StateCode] = '1536')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DN_OUT_ACTIVE_ONHOLD', '1536', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DN_IN_ONHOLD' AND [StateCode] = '2048')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DN_IN_ONHOLD', '2048', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DN_IN_ACTIVE' AND [StateCode] = '4096')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DN_IN_ACTIVE', '4096', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NACD_ONHOLD' AND [StateCode] = '8192')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NACD_ONHOLD', '8192', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'Outbound DN Call' AND [StateCode] = '8704')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'Outbound DN Call', '8704', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NACD_ACTIVE' AND [StateCode] = '16384')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NACD_ACTIVE', '16384', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACD_ONHOLD' AND [StateCode] = '32768')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACD_ONHOLD', '32768', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACD_ACTIVE' AND [StateCode] = '65536')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACD_ACTIVE', '65536', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'NGCC_WALKAWAY' AND [StateCode] = '131072')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'NGCC_WALKAWAY', '131072', @default_state_group, @platform_type_id) 