DECLARE @default_state_group uniqueidentifier
DECLARE @platform_type_id uniqueidentifier
SET @default_state_group = (SELECT TOP 1 Id FROM RtaStateGroup WHERE DefaultStateGroup = 1 AND IsDeleted = 0)
SET @platform_type_id = '7D5FB662-F405-49F4-A4C1-734899693FDA' -- Avaya

IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'UNKNOWN' AND [StateCode] = '0')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'UNKNOWN', '0', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'UNSTAFF' AND [StateCode] = '100')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'UNSTAFF', '100', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AVAIL' AND [StateCode] = '200')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AVAIL', '200', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AVAIL IN' AND [StateCode] = '210')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AVAIL IN', '210', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AVAIL OUT' AND [StateCode] = '220')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AVAIL OUT', '220', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACD' AND [StateCode] = '300')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACD', '300', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACD IN' AND [StateCode] = '310')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACD IN', '310', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACD OUT' AND [StateCode] = '320')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACD OUT', '320', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACW' AND [StateCode] = '400')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACW', '400', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACW IN' AND [StateCode] = '410')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACW IN', '410', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ACW OUT' AND [StateCode] = '420')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ACW OUT', '420', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX' AND [StateCode] = '500')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX', '500', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX1' AND [StateCode] = '501')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX1', '501', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX2' AND [StateCode] = '502')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX2', '502', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX3' AND [StateCode] = '503')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX3', '503', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX4' AND [StateCode] = '504')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX4', '504', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX5' AND [StateCode] = '505')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX5', '505', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX6' AND [StateCode] = '506')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX6', '506', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX7' AND [StateCode] = '507')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX7', '507', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX8' AND [StateCode] = '508')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX8', '508', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX9' AND [StateCode] = '509')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX9', '509', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX IN' AND [StateCode] = '510')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX IN', '510', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX1 IN' AND [StateCode] = '511')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX1 IN', '511', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX2 IN' AND [StateCode] = '512')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX2 IN', '512', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX3 IN' AND [StateCode] = '513')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX3 IN', '513', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX4 IN' AND [StateCode] = '514')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX4 IN', '514', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX5 IN' AND [StateCode] = '515')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX5 IN', '515', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX6 IN' AND [StateCode] = '516')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX6 IN', '516', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX7 IN' AND [StateCode] = '517')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX7 IN', '517', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX8 IN' AND [StateCode] = '518')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX8 IN', '518', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX9 IN' AND [StateCode] = '519')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX9 IN', '519', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX OUT' AND [StateCode] = '520')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX OUT', '520', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX1 OUT' AND [StateCode] = '521')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX1 OUT', '521', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX2 OUT' AND [StateCode] = '522')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX2 OUT', '522', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX3 OUT' AND [StateCode] = '523')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX3 OUT', '523', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX4 OUT' AND [StateCode] = '524')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX4 OUT', '524', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX5 OUT' AND [StateCode] = '525')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX5 OUT', '525', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX6 OUT' AND [StateCode] = '526')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX6 OUT', '526', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX7 OUT' AND [StateCode] = '527')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX7 OUT', '527', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX8 OUT' AND [StateCode] = '528')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX8 OUT', '528', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'AUX9 OUT' AND [StateCode] = '529')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'AUX9 OUT', '529', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACD' AND [StateCode] = '600')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACD', '600', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACD IN' AND [StateCode] = '610')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACD IN', '610', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACD OUT' AND [StateCode] = '620')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACD OUT', '620', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACW' AND [StateCode] = '700')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACW', '700', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACW IN' AND [StateCode] = '710')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACW IN', '710', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'DACW OUT' AND [StateCode] = '720')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'DACW OUT', '720', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'RING' AND [StateCode] = '800')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'RING', '800', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'RING IN' AND [StateCode] = '810')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'RING IN', '810', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'RING OUT' AND [StateCode] = '820')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'RING OUT', '820', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'OTHER' AND [StateCode] = '2200')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'OTHER', '2200', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'OTHER IN' AND [StateCode] = '2210')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'OTHER IN', '2210', @default_state_group, @platform_type_id) 
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'OTHER OUT' AND [StateCode] = '2220')
     INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'OTHER OUT', '2220', @default_state_group, @platform_type_id)