DECLARE @default_state_group uniqueidentifier
DECLARE @platform_type_id uniqueidentifier
SET @default_state_group = (SELECT TOP 1 Id FROM RtaStateGroup WHERE DefaultStateGroup = 1 AND IsDeleted = 0)
SET @platform_type_id = '6DE6DAE4-D70C-43CA-B79B-C879BF64DE45' -- Callguide

IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ready private' AND [StateCode] = '1')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ready private', '1', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ready inquiry' AND [StateCode] = '2')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ready inquiry', '2', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'ready queue' AND [StateCode] = '3')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'ready queue', '3', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'paused private' AND [StateCode] = '4')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'paused private', '4', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'paused inquiry' AND [StateCode] = '5')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'paused inquiry', '5', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'paused queue' AND [StateCode] = '6')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'paused queue', '6', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'onCall private' AND [StateCode] = '7')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'onCall private', '7', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'onCall inquiry' AND [StateCode] = '8')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'onCall inquiry', '8', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'onCall queue' AND [StateCode] = '9')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'onCall queue', '9', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'email private' AND [StateCode] = '10')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'email private', '10', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'email inquiry' AND [StateCode] = '11')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'email inquiry', '11', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'email queue' AND [StateCode] = '12')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'email queue', '12', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'wrapup private' AND [StateCode] = '13')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'wrapup private', '13', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'wrapup inquiry' AND [StateCode] = '14')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'wrapup inquiry', '14', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'wrapup queue' AND [StateCode] = '15')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'wrapup queue', '15', @default_state_group, @platform_type_id)
IF NOT EXISTS (SELECT 1 FROM RtaState WHERE [Name] = 'logout' AND [StateCode] = '16')
	INSERT INTO RtaState ([Id], [Name], [StateCode], [Parent], [PlatformTypeId]) VALUES (NEWID(), 'logout', '16', @default_state_group, @platform_type_id)